image: registry.nic.cz/turris/reforis/reforis/reforis-image

stages:
  - test

before_script:
  - apt-get update && apt-get -y install sudo make curl git
  - make prepare-dev

test:
  stage: test
  script:
    - make test

test-js-build:
  stage: test
  script:
    - cd js
    - npm install
    - npm run-script build -- -o /tmp/app.min.js

lint:
  stage: test
  script:
    - make lint


